name: BDD CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          sudo apt install build-essential linux-headers-6.8.0-1010-azure
          make
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: lint
        run: |
          curl -O https://raw.githubusercontent.com/torvalds/linux/master/scripts/checkpatch.pl
          sudo chmod u+x ./checkpatch.pl ./scripts/linter.sh
          ./scripts/linter.sh
  integrate:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: integrate
        run: |
          make && sudo make ins
          echo -n "sdb" | sudo tee /sys/module/bdd/parameters/set_name
          sudo python3 ./scripts/test.py sdb
          sleep 5
          sudo make rm
